Repository Roots-and-Fruits/RootsAndFruitsDeliveryServiceClient, pull requests merged in 2024-09, with the labels that each got.

#8 [Feat/#7] 퍼널 구조 세팅 완성
  src/App.tsx
  src/constants/routePath.ts
  src/hooks/index.ts
  src/hooks/useFunnel.tsx
  src/pages/orderInfo/components/OrderInfo/OrderInfo.tsx
  src/pages/orderInfo/components/steps/CheckInfo/CheckInfo.style.ts
  src/pages/orderInfo/components/steps/CheckInfo/CheckInfo.tsx
  src/pages/orderInfo/components/steps/Complete/Complete.style.ts
  src/pages/orderInfo/components/steps/Complete/Complete.tsx
  src/pages/orderInfo/components/steps/Receiver1/Receiver1.style.ts
  src/pages/orderInfo/components/steps/Receiver1/Receiver1.tsx
  src/pages/orderInfo/components/steps/Receiver2/Receiver2.style.ts
  src/pages/orderInfo/components/steps/Receiver2/Receiver2.tsx
  src/pages/orderInfo/components/steps/SelectDeliveryDate/SelectDeliveryDate.style.ts
  src/pages/orderInfo/components/steps/SelectDeliveryDate/SelectDeliveryDate.tsx
  src/pages/orderInfo/components/steps/SelectProduct/SelectProduct.style.ts
  src/pages/orderInfo/components/steps/SelectProduct/SelectProduct.tsx
  src/pages/orderInfo/components/steps/Sender/Sender.style.ts
  src/pages/orderInfo/components/steps/Sender/Sender.tsx
  src/pages/orderInfo/page/OrderInfoPage/OrderInfoPage.tsx
  src/routes/index.ts
  src/routes/orderInfoRoutes.tsx
  src/types/index.ts
  src/types/nextStep.ts
Labels: Setting

#10 [Feat/#9] 헤더, 프로그레스바 컴포넌트 구현
  public/svg/ic_back.svg
  src/assets/svg/IcBack.tsx
  src/assets/svg/index.ts
  src/components/common/Header/Header.style.ts
  src/components/common/Header/Header.tsx
  src/components/common/ProgressBar/ProgressBar.style.ts
  src/components/common/ProgressBar/ProgressBar.tsx
  src/components/common/index.ts
  src/pages/Home/Home.tsx
  src/pages/orderInfo/components/steps/CheckInfo/CheckInfo.tsx
  src/pages/orderInfo/components/steps/Complete/Complete.tsx
  src/pages/orderInfo/components/steps/Receiver1/Receiver1.tsx
  src/pages/orderInfo/components/steps/Receiver2/Receiver2.tsx
  src/pages/orderInfo/components/steps/SelectDeliveryDate/SelectDeliveryDate.tsx
  src/pages/orderInfo/components/steps/SelectProduct/SelectProduct.tsx
  src/pages/orderInfo/components/steps/Sender/Sender.tsx
Labels: Feat

#12 [Feat/#11] Input 컴포넌트 구현
  src/components/common/Input/Input.style.ts
  src/components/common/Input/Input.tsx
Labels: Feat

#14 [Feat/#13] Sender 컴포넌트 구현
  package.json
  public/svg/ic_checkbox.svg
  public/svg/ic_checkedTrue.svg
  src/assets/svg/IcCheckbox.tsx
  src/assets/svg/IcCheckedTrue.tsx
  src/assets/svg/index.ts
  src/components/common/CheckBox/CheckBox.style.ts
  src/components/common/CheckBox/CheckBox.tsx
  src/components/common/Header/Header.style.ts
  src/components/common/Header/Header.tsx
  src/components/common/Input/Input.tsx
  src/components/common/ProgressBar/ProgressBar.style.ts
  src/components/common/index.ts
  src/pages/orderInfo/components/steps/Sender/Sender.style.ts
  src/pages/orderInfo/components/steps/Sender/Sender.tsx
  src/pages/orderInfo/hooks/useOrderPostDataChange.ts
  src/pages/orderInfo/hooks/useOrderPostDataValidation.ts
  src/stores/index.ts
  src/stores/orderPostData.ts
  src/styles/theme.ts
  src/types/index.ts
  src/types/orderPostDataType.ts
  src/utils/index.ts
  src/utils/phoneNumber.ts
  tsconfig.app.json
  yarn.lock
Labels: Feat

#19 [Feat/#18] Receiver2 컴포넌트 완성
  package.json
  src/pages/orderInfo/components/steps/Receiver1/Receiver1.tsx
  src/pages/orderInfo/components/steps/Receiver2/Receiver2.style.ts
  src/pages/orderInfo/components/steps/Receiver2/Receiver2.tsx
  src/pages/orderInfo/components/steps/Sender/Sender.tsx
  src/pages/orderInfo/hooks/useOrderPostDataValidation.ts
  src/pages/orderInfo/styles/common.style.ts
  src/pages/orderInfo/styles/index.ts
  yarn.lock
Labels: Feat

#21 [Feat/#20] 주소 등록 연결
  src/components/common/Input/Input.tsx
  src/pages/orderInfo/components/steps/Receiver2/Receiver2.style.ts
  src/pages/orderInfo/components/steps/Receiver2/Receiver2.tsx
  src/pages/orderInfo/components/steps/SelectProduct/SelectProduct.tsx
  src/pages/orderInfo/hooks/useOrderPostDataValidation.ts
Labels: Feat

#23 [Feat/#22] 상품 선택 페이지 퍼블리싱
  public/svg/ic_minus.svg
  public/svg/ic_plus.svg
  src/assets/svg/IcMinus.tsx
  src/assets/svg/IcPlus.tsx
  src/assets/svg/index.ts
  src/components/common/CountProduct/CountProduct.style.ts
  src/components/common/CountProduct/CountProduct.tsx
  src/components/common/index.ts
  src/pages/orderInfo/components/steps/SelectProduct/SelectProduct.style.ts
  src/pages/orderInfo/components/steps/SelectProduct/SelectProduct.tsx
  src/styles/theme.ts
Labels: Feat

#25 [Feat/#24] 희망 배송날짜 선택 페이지 컴포넌트 구현
  package.json
  src/components/common/CustomCalendar/CustomCalendar.tsx
  src/components/common/RadioInput/RadioInput.style.ts
  src/components/common/RadioInput/RadioInput.tsx
  src/components/common/index.ts
  src/pages/orderInfo/components/steps/CheckInfo/CheckInfo.tsx
  src/pages/orderInfo/components/steps/SelectDeliveryDate/SelectDeliveryDate.style.ts
  src/pages/orderInfo/components/steps/SelectDeliveryDate/SelectDeliveryDate.tsx
  src/pages/orderInfo/hooks/useOrderPostDataChange.ts
  yarn.lock
Labels: Feat

#27 [Feat/#26] 입력 정보 확인 페이지 컴포넌트 완성
  public/svg/ic_fix.svg
  src/assets/svg/IcFix.tsx
  src/assets/svg/index.ts
  src/components/common/Button/Button.style.ts
  src/components/common/Button/Button.tsx
  src/constants/routePath.ts
  src/pages/orderInfo/components/steps/CheckInfo/CheckInfo.style.ts
  src/pages/orderInfo/components/steps/CheckInfo/CheckInfo.tsx
  src/pages/orderInfo/components/steps/CheckInfo/Edit/Edit.tsx
  src/pages/orderInfo/components/steps/Receiver1/Receiver1.tsx
  src/pages/orderInfo/hooks/useOrderPostDataChange.ts
  src/pages/orderInfo/styles/common.style.ts
  src/routes/orderInfoRoutes.tsx
  src/stores/currentRecipientIndex.ts
  src/stores/index.ts
  src/styles/theme.ts
Labels: Feat

#31 [Feat/#30] 주문 완료 페이지 퍼블리싱 완료
  public/svg/ic_complete.svg
  src/assets/svg/IcComplete.tsx
  src/assets/svg/index.ts
  src/pages/orderInfo/components/steps/Complete/Complete.style.ts
  src/pages/orderInfo/components/steps/Complete/Complete.tsx
Labels: Feat

#33 [Fix/#32] 주문 정보 수정 및 완료 페이지 수정
  index.html
  public/svg/ic_clipboard-copy.svg
  src/assets/svg/IcClipboardCopy.tsx
  src/assets/svg/index.ts
  src/components/common/ClipboardButton/ClipboardButton.style.ts
  src/components/common/ClipboardButton/ClipboardButton.tsx
  src/components/common/Header/Header.style.ts
  src/components/common/Header/Header.tsx
  src/components/common/Toast/Toast.style.ts
  src/components/common/Toast/Toast.tsx
  src/components/common/index.ts
  src/hooks/useToast.ts
  src/pages/orderInfo/components/steps/CheckInfo/CheckInfo.tsx
  src/pages/orderInfo/components/steps/CheckInfo/Edit/EditReceiver/EditReceiver.style.ts
  src/pages/orderInfo/components/steps/CheckInfo/Edit/EditReceiver/EditReceiver.tsx
  src/pages/orderInfo/components/steps/Complete/Complete.style.ts
  src/pages/orderInfo/components/steps/Complete/Complete.tsx
  src/pages/orderInfo/components/steps/SelectProduct/SelectProduct.tsx
  src/styles/theme.ts
  src/types/index.ts
  tsconfig.node.tsbuildinfo
  vite.config.d.ts
  vite.config.js
Labels: Fix

#38 [Fix/#37] 뒤로가기 클릭시 주소정보 가져오도록 수정
  src/pages/orderInfo/components/steps/Receiver2/Receiver2.tsx
Labels: Fix

#40 [Feat/#39] 상품 선택 페이지 구현 및 최종 post 요청 성공
  src/apis/domains/service/useFetchProductList.ts
  src/apis/queryKeys/queryKeys.ts
  src/components/common/CheckBox/CheckBox.style.ts
  src/components/common/CheckBox/CheckBox.tsx
  src/components/common/CountProduct/CountProduct.style.ts
  src/components/common/CountProduct/CountProduct.tsx
  src/pages/orderInfo/components/steps/CheckInfo/CheckInfo.style.ts
  src/pages/orderInfo/components/steps/CheckInfo/CheckInfo.tsx
  src/pages/orderInfo/components/steps/CheckInfo/Edit/EditReceiver/EditReceiver.style.ts
  src/pages/orderInfo/components/steps/CheckInfo/Edit/EditReceiver/EditReceiver.tsx
  src/pages/orderInfo/components/steps/Receiver1/Receiver1.tsx
  src/pages/orderInfo/components/steps/SelectDeliveryDate/SelectDeliveryDate.tsx
  src/pages/orderInfo/components/steps/SelectProduct/SelectProduct.style.ts
  src/pages/orderInfo/components/steps/SelectProduct/SelectProduct.tsx
  src/pages/orderInfo/hooks/useOrderPostDataChange.ts
  src/stores/index.ts
  src/stores/orderPostData.ts
  src/stores/productList.ts
  src/types/commonType.ts
  src/utils/getDate.ts
  src/utils/index.ts
Labels: Feat

#51 [Feat/#50] 관리자페이지 테이블 hotfix
  src/pages/Admin/components/OrderTable/OrderTable.style.ts
Labels: Fix

#54 [Feat/#52] 주문 조회 태블릿 뷰 퍼블리싱 완료
  public/svg/ic_refresh.svg
  src/App.tsx
  src/assets/svg/IcRefresh.tsx
  src/assets/svg/index.ts
  src/constants/routePath.ts
  src/pages/orderCheck/components/DialButton/DialButton.style.ts
  src/pages/orderCheck/components/DialButton/DialButton.tsx
  src/pages/orderCheck/components/OrderInfoSection/OrderInfoSection.style.ts
  src/pages/orderCheck/components/OrderInfoSection/OrderInfoSection.tsx
  src/pages/orderCheck/components/OrderNumberSearchSection/OrderNumberSearchSection.style.ts
  src/pages/orderCheck/components/OrderNumberSearchSection/OrderNumberSearchSection.tsx
  src/pages/orderCheck/components/OrderTrackingSection/OrderTrackingSection.style.ts
  src/pages/orderCheck/components/OrderTrackingSection/OrderTrackingSection.tsx
  src/pages/orderCheck/components/PayButton/PayButton.style.ts
  src/pages/orderCheck/components/PayButton/PayButton.tsx
  src/pages/orderCheck/components/RecentOrderCard/RecentOrderCard.style.ts
  src/pages/orderCheck/components/RecentOrderCard/RecentOrderCard.tsx
  src/pages/orderCheck/components/index.ts
  src/pages/orderCheck/page/OrderCheckPage.style.ts
  src/pages/orderCheck/page/OrderCheckPage.tsx
  src/routes/index.ts
  src/routes/orderCheckRoutes.tsx
  src/styles/global.ts
  src/styles/theme.ts
Labels: Feat

#56 [Feat/#55] 주문번호로 조회 api 연결 완료
  src/apis/domains/orderCheck/useFetchOrderInfoWithOrderNumber.ts
  src/apis/queryKeys/queryKeys.ts
  src/pages/orderCheck/components/OrderInfoSection/OrderInfoSection.tsx
  src/pages/orderCheck/components/OrderNumberSearchSection/OrderNumberSearchSection.tsx
  src/pages/orderCheck/page/OrderCheckPage.tsx
  src/stores/index.ts
  src/stores/orderInfo.ts
  src/types/index.ts
  src/types/orderInfoWithOrderNumber.ts
Labels: Feat
